### PR TITLE
Update Card UI

### PR DESCRIPTION
**Pull request by hemarina**

### CODE REVIEW

**Comment by gkulin** [comment]
I will say I personally much prefer the +X more tag!

I did a quick comparison with Austin's design and I noticed a few things to update:
image

@Austinauth please feel free to correct me if I'm wrong about anything or add in any other feedback you have

**Comment by Austinauth** [comment]
@gkulin

> I will say I personally much prefer the +X more tag!
> 
> I did a quick comparison with Austin's design and I noticed a few things to update: image
> 
> @Austinauth please feel free to correct me if I'm wrong about anything or add in any other feedback you have

This is great, thank you so much for red lining this out! Agree, I like the +x tag as well

**Review by wbreza — APPROVED** [review]

**Comment by Austinauth** [comment]
Hey @hemarina going to start adding my feedback here. Things are getting really close. There are a couple adjustments I'd like to try that were not part of my initial mock-ups. Thank you for understanding!

## CTA Card
image

Please reach out if you have any questions. We may also want to tweak the color of the text, but for now let's make these changes and see how it looks. Will follow up with feedback on the template cards tomorrow.

**Comment by Austinauth** [comment]
## Template Card

Same as with the CTA Card above. I'm sure there will be some minor final adjustments we need to make after implementing these fixes. Please don't hesitate to reach out with questions. I will be out Friday thru Tuesday. No rush on my end.

### Updated card design

image

### Updated card design adjustments

#### Miscellaneous updates
image

#### Padding & Spacing
image

#### Copy behavior
image

### Useful links
Here are some links you might find useful.
- [Fluent 2: Badge component (Tag)](https://fluent2.microsoft.design/components/web/react/badge/usage)
- [Fluent 2: Tooltip component](https://fluent2.microsoft.design/components/web/react/tooltip/usage)

**Pull request merged**
