### PR TITLE
Add FastAPI, htmx, TailwindCSS Web App with Log Analytics template

### PR DESCRIPTION
**Pull request by tataraba**
Please fill out this template! There are three different types of contributions, feel free to delete the checklists that are not applicable to your contribution type. 

# If you are submitting a new `azd` template to the gallery
Fill this out if you want your template to be added to the awesome-azd gallery!

- [ x ] Added an entry to https://github.com/Azure/awesome-azd/blob/main/website/src/data/users.tsx that includes:
    - [ x ] **Template title** - A short title that reflects the local application stack that someone could use to get their application on Azure (e.g. "Containerized React Web App with Java API and MongoDB")
    - [ x ] **Description** - 1-2 sentence description of the architecture (e.g. Azure services) or solution that is defined by the template.
    - [ x ] **Architecture Diagram or Application Screenshot** - Used as display image for gallery card. The image should include all services and their connections ([example](https://github.com/Azure-Samples/todo-csharp-sql/blob/main/assets/resources.png)). You should add the image to the `website/src/data/images/`.
    - [ x ] **Link to Author's GitHub or other relevant website** - Used for attribution
    - [ x ] **Author's Name** -  Name to credit on the gallery card
    - [ x ] **Link to template source** - Link to the template GitHub repo 
    - [ x ] **Tags** - One or more [tags](https://github.com/Azure/awesome-azd/blob/main/website/src/data/tags.tsx) representing the template. Provide at least 1 tag for programming language used and at least 1 tag for Azure services integrated. Also tag the IaC provider (Bicep or Terraform). If you don't see a relevant tag for your template? Feel free to add one!

- [ x ] In the PR comment, if you can also add a link to the PR where you made your repo `azd` compatible this will allow us to provide feedback on your template and speed up the review process.

No direct PR, but here's a [link to the commit](https://github.com/tataraba/musicbinder-azd/commit/91d30c605708238e160b535e056e72f72da00f68) that added most of the stuff for `azd` with only one modification made afterwards on the uvicorn command.

### CODE REVIEW

**Comment by tataraba** [comment]
@microsoft-github-policy-service agree

**Review by savannahostrowski — APPROVED** [review]
Very awesome sample! Thanks for contributing @tataraba.

@rajeshkamal5050  let's get this tested!

**Comment by rajeshkamal5050** [comment]
> @rajeshkamal5050 let's get this tested!

hey @v-xuto can we test this?

**Comment by v-xuto** [comment]
> > @rajeshkamal5050 let's get this tested!
> 
> hey @v-xuto can we test this?

Sure. We will start testing this template https://github.com/tataraba/musicbinder-azd.

**Comment by v-xuto** [comment]
@rajeshkamal5050 We have completed the testing of this template and filed two issues https://github.com/tataraba/musicbinder-azd/issues/2 and https://github.com/tataraba/musicbinder-azd/issues/3. Please review.

**Comment by tataraba** [comment]
@v-xuto @rajeshkamal5050 
Both of the issues were resolved. 

1) Converted repo to a template repo, so it should show the button as noted in the README
2) I was able to deploy using `azd up` locally, but it wasn't working from Codespaces. Changed the appCommandLine in the bicep file that included single (nested) quotes around the `-` character and changed to double quotes. I was able to successfully deploy locally and from within Codespaces.

Also, added a command in the Dockerfile (for Codespaces) to install the azd CLI.

Let me know if there's anything else.

**Comment by jongio** [comment]
I added comments here: https://github.com/tataraba/musicbinder-azd/commit/91d30c605708238e160b535e056e72f72da00f68

**Comment by tataraba** [comment]
@jongio Made most of the changes recommended on the commit, with exception to using `abbreviations.json`. Can you advise if you'd like abbreviations added to `main.bicep` or if I should just remove `abbreviations.json` altogether to reduce complexity?

**Comment by jongio** [comment]
It is up to you to choose if you want to use abbreviations.json, we use it to help us be consistent across all our templates.  If you don't want to use it, that is fine.  But if you aren't going to use it, then I recommend removing it from your repo.

**Comment by tataraba** [comment]
@jongio I added `abbreviations.json` support and merged to main. Let me know if that looks good or if anything needs to change.

**Review by gkulin — APPROVED** [review]

**Pull request merged**
