### PR TITLE
Update navbar

### LINKED ISSUE #154: Navigation Bar
- [ ] Default Navigation Bar
- [ ] Navigation Bar with search bar

### PR DESCRIPTION
**Pull request by hemarina**
fix #154 

- [x] TODO: Change color on navitem when selected with purple color and border bottom
Note: Templates (default page) cannot add underline. Chatted with Docusaurus discord community.

### CODE REVIEW

**Comment by gkulin** [comment]
it does feel a little weird to not have the underline for Templates. Can you share what the Docusaurus community said about it? is it just impossible to do text decoration on the default page?

**Comment by Austinauth** [comment]
@hemarina  @gkulin 

In our early sketches, we had planned for there to eventually be a "home" page you could visit by clicking the logo + type on the left. That would technically be the default page if we ever decide to implement it. 

In the meantime it is probably okay if clicking the logo takes you to the templates page. That being said, we need to find a work around to make the "Template" nav item purple and underlined when the user is on that page.

We can also remove the purple hover from the logo:
image

**Comment by gkulin** [comment]
> Should we only keep awesome-azd title as default page for now?

@hemarina what would it look like if we did this? awesome-azd title page & template page would essentially be 2 different instances of the template gallery? Meaning if someone went to https://azure.github.io/awesome-azd/ they would be on a page showing templates and then if they clicked "Templates" they would go to https://azure.github.io/awesome-azd/templates which would also show the template list?

If it's not too much work, it would be nice to be able to pull the changes for locally to feel / see how it works. but if it would be as I described above, I feel like that would be confusing?

**Comment by gkulin** [comment]
> @gkulin Grace Kulin FTE Yes, we could do that and make awesome-azd title page & template page to be 2 different instances of the template gallery. I'm not sure if I understand the difference of default page vs templates page. Are they different view types of templates?

never mind about the default vs templates page. I was just confused by what you said but seeing the updates on this pr it all makes sense now!

**Comment by gkulin** [comment]
one thing about the updated navbar, I think the changing the order to:
Getting Started | **Contribute** | Docs  | Resources

might make a bit more sense / be a better experience because Getting Started & Contribute both stay _within_ awesome-azd (so should be grouped together) while Resources & Docs both redirect to _outside_ of awesome-azd

**Comment by Austinauth** [comment]
> > I'm not sure I understand the question.
> 
> Clicking on logo or "awesome-azd" will lead user to default page (template gallery). "Templates" page also leads user to default page. How about not having "templates" page as logo or "awesome-azd" tab do the same? That screenshot shows nav bar without "Templates" tab.

Ah I understand now. I think we need to keep the "templates" navigation item. It is the most critical element of the site. Without it, users may not understand how to get back to the templates if they navigate to a different page.

**Comment by gkulin** [comment]
@hemarina 
I think there is a bug somewhere in this pr. There is a duplicate "submit your template" button that wasn't there the last time I pulled these changes
image

**Pull request merged**
