### PR TITLE
Add java spring apps + openai app template

### PR DESCRIPTION
**Pull request by aarthiem**
Please fill out this template! There are three different types of contributions, feel free to delete the checklists that are not applicable to your contribution type. 

# If you are submitting a new `azd` template to the gallery
Fill this out if you want your template to be added to the awesome-azd gallery!

### Your template repository
Place your template repository link here:
https://github.com/Azure-Samples/app-templates-java-openai-springapps

- [ ] Added an entry to https://github.com/Azure/awesome-azd/blob/main/website/src/data/users.tsx that includes:
    - [x ] **Template title** - A short title that reflects the local application stack that someone could use to get their application on Azure (e.g. "Containerized React Web App with Java API and MongoDB")
    - [x ] **Description** - 1-2 sentence description of the architecture (e.g. Azure services) or solution that is defined by the template.
    - [ x] **Architecture Diagram or Application Screenshot** - Used as display image for gallery card. The image should include all services and their connections ([example](https://github.com/Azure-Samples/todo-csharp-sql/blob/main/assets/resources.png)). You should add the image to the `website/src/data/images/`.
    - [ x] **Link to Author's GitHub or other relevant website** - Used for attribution
    - [ x] **Author's Name** -  Name to credit on the gallery card
    - [x ] **Link to template source** - Link to the template GitHub repo 
    - [x ] **Tags** - One or more [tags](https://github.com/Azure/awesome-azd/blob/main/website/src/data/tags.tsx) representing the template. Provide at least 1 tag for programming language used and at least 1 tag for Azure services integrated. Also tag the IaC provider (Bicep or Terraform). If you don't see a relevant tag for your template? Feel free to add one!

- [ ] In the PR comment, if you can also add a link to the PR where you made your repo `azd` compatible this will allow us to provide feedback on your template and speed up the review process.

# If you are submitting a resource to be added to the awesome-azd README:
- [ ] Name of resource
- [ ] Resource author - who created this resource? (so we can credit them!)
- [ ] What section should this resource be included in? -Is the resource an article? A video? Something else?

### CODE REVIEW

**Comment by v-xuto** [comment]
> @v-xuto Would you mind testing this template?

Sure. We will start testing this template today.

**Comment by v-xuto** [comment]
@hemarina, @aarthiem We have finished this template test, and we filed one issue. Please review.
- https://github.com/Azure-Samples/app-templates-java-openai-springapps/issues/34

**Comment by pmalarme** [comment]
> @hemarina, @aarthiem We have finished this template test, and we filed one issue. Please review.
> 
> * [Unable to run and debug locally with Visual Studio Code Azure-Samples/app-templates-java-openai-springapps#34](https://github.com/Azure-Samples/app-templates-java-openai-springapps/issues/34)

The resolution has been merged in the main branch

**Comment by v-xuto** [comment]
@hemarina Issue https://github.com/Azure-Samples/app-templates-java-openai-springapps/issues/34 has been fixed, currently this template has no issues.

**Review by gkulin — APPROVED** [review]

**Pull request merged**
