### PR TITLE
Submission for Pinecone Assistant app, pinecone-assistant-azd.

### PR DESCRIPTION
**Pull request by cwaddingham**
Please fill out this template! There are three different types of contributions, feel free to delete the checklists that are not applicable to your contribution type. 

# If you are submitting a new `azd` template to the gallery

This template will help people trying out the Pinecone Assistant via Azure to get up and running in minutes. 

### Your template repository
[Place your template repository link here:
](https://github.com/pinecone-io/pinecone-assistant-azd)

- [ x] Added an entry to https://github.com/Azure/awesome-azd/blob/main/website/src/data/users.tsx that includes:
    - [x ] **Template title** - A short title that reflects the local application stack that someone could use to get their application on Azure (e.g. "Containerized React Web App with Java API and MongoDB")
    - [x ] **Description** - 1-2 sentence description of the architecture (e.g. Azure services) or solution that is defined by the template.
    - [x ] **Architecture Diagram or Application Screenshot** - The image should include all services and their connections ([example](https://github.com/Azure-Samples/todo-csharp-sql/blob/main/assets/resources.png)). You should add the image to the `website/src/data/images/`.
    - [ x] **Link to Author's GitHub or other relevant website** - Used for attribution
    - [x ] **Author's Name** -  Name to credit on the gallery card
    - [ x] **Link to template source** - Link to the template GitHub repo 
    - [ x] **Tags** - Specify [tags](https://github.com/Azure/awesome-azd/blob/main/website/src/data/tags.tsx) to represent the template. If you don't see a relevant tag for your template? Feel free to add one!
        
        **Required tags**:
      - [x ] Tag your template as Micrsoft-authored (`"msft"`) or Community-authored (`"community"`)
      - [x ] Tag the IaC provider (`"bicep"` or `"terraform"`)
      - [x ] At least 1 tag for programming language used
      - [x ] At least 1 tag for Azure services integrated
      - [x ] Add the `"new"` tag for any newly authored templates

- [ x] In the PR comment, if you can also add a link to the PR where you made your repo `azd` compatible this will allow us to provide feedback on your template and speed up the review process.
- [ ] If the template is Microsoft-authored, we encourage you to also [publish it to learn.microsoft.com/samples](https://review.learn.microsoft.com/en-us/help/contribute/samples/process/onboarding?branch=main).

# If you are submitting a resource to be added to the awesome-azd README:
- [ ] Name of resource
- [ ] Resource author - who created this resource? (so we can credit them!)
- [ ] What section should this resource be included in? -Is the resource an article? A video? Something else?

### CODE REVIEW

**Comment by v-xuto** [comment]
> @v-xuto Could you test this template please?

@hemarina, @cwaddingham We have finished this template test, and we filed five issues. Please review.
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/4
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/5
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/6
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/7
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/8

**Comment by v-xuto** [comment]
@cwaddingham  After you fixed, we retested this template and filed four issues. Please review.

- https://github.com/pinecone-io/pinecone-assistant-azd/issues/10
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/11
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/12
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/13

**Comment by v-xuto** [comment]
@cwaddingham This issue12 has not been fixed and can still be reproduced, please review.
- https://github.com/pinecone-io/pinecone-assistant-azd/issues/12

**Comment by cwaddingham** [comment]
@v-xuto all issues have been identified and resolved. Please let me know when you've had a chance to publish this revision.

**Comment by v-xuto** [comment]
> @v-xuto all issues have been identified and resolved. Please let me know when you've had a chance to publish this revision.

@cwaddingham There is a small issue in Mac env, please check the [comment](https://github.com/pinecone-io/pinecone-assistant-azd/issues/12#issuecomment-2314743691) and fix it.

**Review by gkulin — APPROVED** [review]

**Pull request merged**
