### PR TITLE
Adds bicep & terraform starter templates

### PR DESCRIPTION
**Pull request by wbreza**
Adds bicep & terraform starter templates into Awesome AZD
Fixes azure/azure-dev#2794

### CODE REVIEW

**Review by savannahostrowski — APPROVED** [review]
LGTM -  @gkulin for input as well

**Review by vhvb1989 — APPROVED** [review]

**Comment by vhvb1989** [comment]
Note:  There should be a `version` that `azd` points to.  It does not feel right to use the latest `main` as it is vulnerable to regressions

**Review by rajeshkamal5050 — APPROVED** [review]

**Comment by wbreza** [comment]
> Note: There should be a `version` that `azd` points to. It does not feel right to use the latest `main` as it is vulnerable to regressions

The awesome-azd template source uses an aks.ms link `https://aka.ms/awesome-azd/templates.json`. Right now this points to `main` branch in awesome-azd repo.  Main should be treated as last known good.

**Comment by vhvb1989** [comment]
> > Note: There should be a `version` that `azd` points to. It does not feel right to use the latest `main` as it is vulnerable to regressions
> 
> The awesome-azd template source uses an aks.ms link `https://aka.ms/awesome-azd/templates.json`. Right now this points to `main` branch in awesome-azd repo. Main should be treated as last known good.

Yeah, that's what I see as an anti-pattern there.
There should be one `aks.ms` that point to `latest` (or daily) which folks can register to receive updated immediately.
And there should be one `aks.ms` for each repo-release. This helps to freeze the list of templates and avoid unexpected changes

**Pull request merged**
