### PR TITLE
Simple fastapi snow azd

### PR DESCRIPTION
**Pull request by MiguelElGallo**
Please fill out this template! There are three different types of contributions, feel free to delete the checklists that are not applicable to your contribution type. 

# If you are submitting a new `azd` template to the gallery
Fill this out if you want your template to be added to the awesome-azd gallery!

### Your template repository
Place your template repository link here: https://github.com/MiguelElGallo/simple-fastapi-snow-azd

- [X] Added an entry to https://github.com/Azure/awesome-azd/blob/main/website/src/data/users.tsx that includes:
    - [X] **Template title** - A short title that reflects the local application stack that someone could use to get their application on Azure (e.g. "Containerized React Web App with Java API and MongoDB")
    - [X] **Description** - 1-2 sentence description of the architecture (e.g. Azure services) or solution that is defined by the template.
    - [X] **Architecture Diagram or Application Screenshot** - The image should include all services and their connections ([example](https://github.com/Azure-Samples/todo-csharp-sql/blob/main/assets/resources.png)). You should add the image to the `website/src/data/images/`.
    - [X] **Link to Author's GitHub or other relevant website** - Used for attribution
    - [X] **Author's Name** -  Name to credit on the gallery card
    - [X] **Link to template source** - Link to the template GitHub repo 
    - [X] **Tags** - Specify [tags](https://github.com/Azure/awesome-azd/blob/main/website/src/data/tags.tsx) to represent the template. If you don't see a relevant tag for your template? Feel free to add one!
        
        **Required tags**:
      - [X] Tag your template as Micrsoft-authored (`"msft"`) or Community-authored (`"community"`)
      - [X] Tag the IaC provider (`"bicep"` or `"terraform"`)
      - [X] At least 1 tag for programming language used
      - [X] At least 1 tag for Azure services integrated
      - [X] Add the `"new"` tag for any newly authored templates

- [X] In the PR comment, if you can also add a link to the PR where you made your repo `azd` compatible this will allow us to provide feedback on your template and speed up the review process.
https://github.com/MiguelElGallo/simple-fastapi-snow-azd/commit/63d651cad78821faecc77b9a6d6f7c68a17e057f

# If you are submitting a resource to be added to the awesome-azd README:
- [ ] Name of resource
- [ ] Resource author - who created this resource? (so we can credit them!)
- [ ] What section should this resource be included in? -Is the resource an article? A video? Something else?

### CODE REVIEW

**Comment by MiguelElGallo** [comment]
Good morning! Hope this can be merged before the year ends! 
Happy festive season!

**Review by vhvb1989 — APPROVED** [review]
LGTM

**Comment by vhvb1989** [comment]
@MiguelElGallo , Marina is OOF until next year.
We also recently change the publishing model. Even if we merge this PR, the changes won't go to the production site until there is a new release for the entire site.

Is there some reason why you need this asap?

**Comment by MiguelElGallo** [comment]
@vhvb1989 Thanks for checking and letting me know. I will wait then for the next release. Please let me know if something else is needed from my side.

**Comment by v-xuto** [comment]
> @v-xuto Could you test this template?

Sure. We will test this template today.

**Comment by MiguelElGallo** [comment]
> > @v-xuto Could you test this template?
> 
> Sure. We will test this template today.

@v-xuto Thanks for testing! Let me know if you have any comments / questions.

**Comment by MiguelElGallo** [comment]
Hello! Any comments when this will be merged?

**Comment by v-xuto** [comment]
@hemarina, @MiguelElGallo  We have finished this template test, and we filed three issues. Please review.

- https://github.com/MiguelElGallo/simple-fastapi-snow-azd/issues/5
- https://github.com/MiguelElGallo/simple-fastapi-snow-azd/issues/6
- https://github.com/MiguelElGallo/simple-fastapi-snow-azd/issues/7

**Comment by MiguelElGallo** [comment]
Hello @v-xuto ,
Thanks for the issues, now those have been fixed. 
Ping @hemarina 
Enjoy your Friday!

**Comment by MiguelElGallo** [comment]
> LGTM. @MiguelElGallo Thank you for your contribution!

Thanks to you! @hemarina and @v-xuto 

When is this going to be visible?

**Pull request merged**
